    - name: Create Application Server instance
      ec2:
         group: "{{ security_group }}"
         instance_type: "{{instancetype}}"
         image: "{{AMI}}"
         region: "{{region_name}}"
         wait: true
         exact_count: "{{number}}"
         count_tag:
           Name: "{{IAM_groupname}}"
         group_id: "{{ group_id }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         key_name: "{{keypair_name}}"
      register: ec2_result

    - debug:
        msg: "app-server  public ip address is: {{ec2_result.instances[0].public_ip}}"

    - name: wait for ssh to come up
      local_action: wait_for
                    host={{ec2_result.instances[0].public_ip}}
                    port=22
                    state=started
      with_items: ec2.instances

